services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: on-failure
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: on-failure
